"""
null_gallery.py
===============
Generate Fig. X (null gallery) of Terzić (2026): one noise realisation of the case (a) signal trajectory alongside three null model realisations.

This script does two things only:
  1. Generates and saves four trajectories as CSV data files.
  2. Produces the null gallery figure.

It does NOT perform any statistical analysis. The analysis (A_norm, closure and cancellation diagnostics, MC uncertainty propagation, p-values) should be performed separately by running analyse_hysteresis.py on the saved CSV files.

Input
-----
This script reads signal_a.csv produced by signal_gallery.py. Run signal_gallery.py first. The input CSV must have the format:

    # comment lines starting with # are ignored
    F (A.U.),HR,s_F,s_HR
    1.456,1.234,0.073,0.062
    ...

where F and HR are the noise-free signal values and s_F; s_HR are their fractional 1-sigma uncertainties (s_F = sigma_noise * F; s_HR = sigma_noise * HR).

Output files
------------
All written to --outdir (default: results/):

  null_gallery.pdf
      The 2x2 figure with the four panels.

  null_a.csv  -- One noise realisation of the signal
      The noise-free signal perturbed by one draw from N(0; s_F) and N(0; s_HR). This represents one possible actual observation of the underlying signal trajectory. The uncertainties s_F; s_HR are preserved from the input file.

      Format identical to signal_a.csv. Suitable input for analyse_hysteresis.py.

  null_b.csv  -- Permutation null
      The same (F; HR) data points from the noise-free signal; with their time order randomly shuffled. No uncertainties are meaningful for null realisations (they are synthetic); so s_F = s_HR = 0 in this file. analyse_hysteresis.py will skip MC uncertainty propagation and d_closure when s_F = s_HR = 0.

  null_c.csv  -- AR(1) null
      A new pair of time series generated by fitting an AR(1) model to the noise-free signal coordinates and drawing one realisation. s_F = s_HR = 0.

  null_d.csv  -- Fourier phase-randomised null
      A new pair of time series with the same power spectrum as the noise-free signal but randomised phases s_F = s_HR = 0.

Input format for analyse_hysteresis.py
---------------------------------------
analyse_hysteresis.py expects a CSV where the first non-comment line is the header row with four column names (used as axis labels). Rows beginning with '#' are treated as comments and ignored.

For null_b/c/d.csv; s_F = s_HR = 0; so analyse_hysteresis.py will compute A_norm; R_cancel; f_closure but not d_closure or the MC uncertainty interval. Example usage:

    python analyse_hysteresis.py null_a.csv --K_null 10000
    python analyse_hysteresis.py null_b.csv --K_null 10000
    python analyse_hysteresis.py null_c.csv --K_null 10000
    python analyse_hysteresis.py null_d.csv --K_null 10000

Figure description
------------------
Panel (a): grey points with fractional error bars show the noise-free signal from signal_a.csv; coloured points show one noise realisation (saved as null_a.csv).
Panel (b): grey points with error bars show the original signal; coloured points show the permuted trajectory (null_b.csv).
Panels (c) and (d): AR(1) and Fourier null realisations respectively.
  Axes adapt to the range of each null.

The nulls in panels (b)--(d) are derived from the noise-free signal trajectory because the null models operate on the coordinate values, not the measurement noise.

Usage
-----
    python null_gallery.py [--signal_csv results/signal_a.csv]
                           [--outdir results] [--seed 43]

Dependencies
------------
    numpy, matplotlib
    signal_gallery.py    -- must be run first to produce signal_a.csv

Author: T. Terzić <tterzic@phy.uniri.hr>
License: MIT
"""

import argparse
import sys
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

sys.path.insert(0, str(Path(__file__).parent))

plt.rcParams.update({
    "font.family"    : "serif",
    "font.size"      : 8,
    "axes.labelsize" : 8,
    "axes.titlesize" : 8,
    "xtick.direction": "in",
    "ytick.direction": "in",
    "xtick.top"      : True,
    "ytick.right"    : True,
    "xtick.labelsize": 7,
    "ytick.labelsize": 7,
    "figure.dpi"     : 200,
})


# ---------------------------------------------------------------------------
# CSV I/O
# ---------------------------------------------------------------------------

def load_csv(path):
    """
    Load a trajectory CSV file produced by signal_gallery.py or null_gallery.py.

    The first non-comment line is the header row. Its four comma-separated values are the axis labels used in figures and output tables. All subsequent lines are data rows read by column position (0=x; 1=y; 2=sx; 3=sy).
    Comment lines (starting with #) are skipped.

    Returns
    -------
    x, y, sx, sy : ndarray
        x = col 0; y = col 1; sx = col 2; sy = col 3.
    x_label, y_label : str
        Axis labels extracted from the header row.
    """
    x, y, sx, sy = [], [], [], []
    header = None
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if header is None:
                header = line.split(",")
                continue
            parts = line.split(",")
            x.append(float(parts[0]))
            y.append(float(parts[1]))
            sx.append(float(parts[2]))
            sy.append(float(parts[3]))
    x_label = header[0].strip() if header else "x"
    y_label = header[1].strip() if header else "y"
    return np.array(x), np.array(y), np.array(sx), np.array(sy), x_label, y_label


def save_csv(x, y, sx, sy, label, description, path):
    """
    Save a trajectory to a CSV file readable by analyse_hysteresis.py.

    The first non-comment line is the header row. Its four comma-separated values are used as axis labels in figures and output tables.
    For null realisations (permutation; AR(1); Fourier); sx = sy = 0 because these are synthetic trajectories with no measurement process.
    analyse_hysteresis.py will skip d_closure and MC propagation when sx = sy = 0.

    Parameters
    ----------
    x, y : ndarray        F and HR coordinates
    sx, sy : ndarray      1-sigma uncertainties on x and y
    label : str           Short label; e.g. '(b) Permutation null'
    description : str     One-line description of the null model
    path : str or Path    Output file path
    """
    with open(path, "w") as fh:
        fh.write(f"# Trajectory: {label}\n")
        fh.write(f"# {description}\n")
        fh.write("# Generated by null_gallery.py\n")
        fh.write("# Columns: F (A.U.); HR; s_F; s_HR\n")
        fh.write("# F (A.U.) : flux (normalised to quiescent = 1)\n")
        fh.write("# HR       : hardness ratio (normalised to quiescent = 1)\n")
        fh.write("# s_F      : 1-sigma uncertainty on F (0 for synthetic null realisations)\n")
        fh.write("# s_HR     : 1-sigma uncertainty on HR (0 for synthetic null realisations)\n")
        fh.write(f"# To analyse: python analyse_hysteresis.py {Path(path).name} --K_null 10000\n")
        fh.write("F (A.U.),HR,s_F,s_HR\n")
        for i in range(len(x)):
            fh.write(f"{x[i]:.6f},{y[i]:.6f},{sx[i]:.6f},{sy[i]:.6f}\n")


# ---------------------------------------------------------------------------
# Null model generators (single realisations, for figure and CSV only)
#
# These generate one realisation of each null model for visualisation.
# The scientific null distributions (K realisations) are computed by hysteresis_core.null_permutation/ar1/fourier via analyse_hysteresis.py.
# ---------------------------------------------------------------------------

def _null_permutation_once(x, y, rng):
    """Permutation null: shuffle time order of (x, y) pairs jointly."""
    idx = rng.permutation(len(x))
    return x[idx], y[idx]


def _null_ar1_once(x, y, rng):
    """
    AR(1) null: generate one pair of independent AR(1) series with parameters estimated from x and y by the Yule-Walker method.
    The first point is drawn from the stationary distribution N(mu, std^2).
    """
    N = len(x)

    def _ar1_series(ts):
        ts_c = ts - ts.mean()
        denom = np.dot(ts_c[:-1], ts_c[:-1])
        phi = np.dot(ts_c[:-1], ts_c[1:]) / denom if denom > 0 else 0.0
        phi = np.clip(phi, -0.99, 0.99)
        sigma = np.std(ts_c) * np.sqrt(1 - phi**2)
        mu, std = ts.mean(), np.std(ts)
        out = np.empty(N)
        out[0] = rng.normal(mu, std)
        eps = rng.normal(0, sigma, N)
        for i in range(1, N):
            out[i] = phi * (out[i-1] - mu) + mu + eps[i]
        return out

    return _ar1_series(x), _ar1_series(y)


def _null_fourier_once(x, y, rng):
    """
    Fourier phase-randomisation null: preserve amplitude spectrum of each series, randomise phases independently (Timmer & König 1995).
    DC and Nyquist components are kept real to ensure real-valued output.
    """
    N = len(x)

    def _fourier_series(ts):
        fft_z = np.fft.rfft(ts)
        phases = rng.uniform(0, 2 * np.pi, len(fft_z))
        phases[0] = 0.0           # DC component must be real
        if N % 2 == 0:
            phases[-1] = 0.0      # Nyquist component must be real for even N
        return np.fft.irfft(np.abs(fft_z) * np.exp(1j * phases), n=N)

    return _fourier_series(x), _fourier_series(y)


# ---------------------------------------------------------------------------
# Draw one panel
# ---------------------------------------------------------------------------

def draw_panel(ax, x, y, title, x_label="x", y_label="y",
               x_orig=None, y_orig=None, sx_orig=None, sy_orig=None):
    """
    Draw one trajectory panel.
    x = x-axis values, y = y-axis values.
    x_label and y_label are used as axis labels (from the CSV header row).

    If x_orig/y_orig are provided, the original (noise-free) signal points are shown in grey with error bars underneath the coloured trajectory.
    This applies to panels (a) and (b):
      - panel (a): shows that the noise realisation stays close to the original points within the measurement uncertainties.
      - panel (b): shows that the permutation uses the same points as the original; only their chronological ordering changes.
    sx_orig = uncertainties on x; sy_orig = uncertainties on y.
    """
    N = len(x)
    cmap   = plt.get_cmap("viridis")
    colors = cmap(np.linspace(0.15, 0.90, N))

    # Original (noise-free) signal in grey with error bars (panels a and b only)
    if x_orig is not None:
        for i in range(len(x_orig)):
            ax.errorbar(x_orig[i], y_orig[i], xerr=sx_orig[i], yerr=sy_orig[i],
                        fmt="none", ecolor="0.75", elinewidth=0.6,
                        capsize=1.5, capthick=0.6, zorder=1)
        ax.scatter(x_orig, y_orig, color="0.75", s=18, linewidths=0, zorder=2)
        ax.plot(x_orig, y_orig, "-", color="0.85", lw=0.7, zorder=3)

    ax.plot(x, y, "-", color="0.78", lw=0.7, zorder=3)

    for i in range(N):
        ax.scatter(x[i], y[i], color=colors[i], s=12, linewidths=0, zorder=4)

    ax.scatter(x[0],  y[0],  marker="o", s=20, color=colors[0],
               edgecolors="k", linewidths=0.5, zorder=5)
    ax.scatter(x[-1], y[-1], marker="s", s=20, color=colors[-1],
               edgecolors="k", linewidths=0.5, zorder=5)

    # Direction arrow at the largest gap between consecutive points
    dists = np.sqrt(np.diff(x)**2 + np.diff(y)**2)
    i_arr = int(np.argmax(dists))
    ax.annotate("", xy=(x[i_arr+1], y[i_arr+1]),
                xytext=(x[i_arr], y[i_arr]),
                arrowprops=dict(arrowstyle="-|>", color="0.25",
                                lw=1.0, mutation_scale=10))

    ax.set_title(title, fontsize=7, pad=3)
    ax.set_xlabel(x_label, fontsize=7)
    ax.set_ylabel(y_label, fontsize=7)
    ax.tick_params(labelsize=6)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def plot_null_gallery(
    signal_csv : str = "results/signal_a.csv",
    seed       : int = 43,
    outdir     : str = "results",
):
    """
    Generate the null gallery figure and save all four trajectories as CSV.

    Reads the noise-free signal trajectory from signal_a.csv (produced by signal_gallery.py) and generates:
      (a) One noise realisation using the uncertainties from the CSV
      (b) One permutation null realisation
      (c) One AR(1) null realisation
      (d) One Fourier null realisation

    The nulls in (b)--(d) are derived from the noise-free signal because null models operate on the coordinate values, not the measurement noise.
    Use a different seed from signal_gallery.py so the noise realisation in panel (a) is independent.

    Parameters
    ----------
    signal_csv : str    Path to signal_a.csv from signal_gallery.py
    seed : int          Random seed
    outdir : str        Output directory
    """
    rng = np.random.default_rng(seed)
    Path(outdir).mkdir(parents=True, exist_ok=True)

    print(f"Reading signal from: {signal_csv}")
    x_true, y_true, sx_true, sy_true, x_label, y_label = load_csv(signal_csv)
    N = len(x_true)
    print(f"  N = {N} points")

    # --- Generate the four trajectories ---

    # (a) One noise realisation: perturb the noise-free values by one draw from their uncertainty distributions. Preserves original uncertainties.
    x_a = x_true + rng.normal(0, 1, N) * sx_true
    y_a = y_true + rng.normal(0, 1, N) * sy_true

    # (b) Permutation null: same points, time order randomly shuffled. Derived from the noise-free trajectory.
    x_b, y_b = _null_permutation_once(x_true, y_true, rng)

    # (c) AR(1) null: independent AR(1) series fitted to the noise-free trajectory.
    x_c, y_c = _null_ar1_once(x_true, y_true, rng)

    # (d) Fourier null: matched power spectrum, randomised phases. Derived from the noise-free trajectory.
    x_d, y_d = _null_fourier_once(x_true, y_true, rng)

    zeros = np.zeros(N)

    # --- Save CSV files ---
    # null_a.csv has the original uncertainties (sx, sy from signal_a.csv).
    # null_b/c/d.csv have sx = sy = 0 (synthetic null realisations).
    csv_specs = [
        (x_a, y_a, sx_true, sy_true,
         "(a) Signal (noise realisation)",
         "One noise realisation: x_true + N(0; sx); y_true + N(0; sy)",
         "null_a.csv"),
        (x_b, y_b, zeros, zeros,
         "(b) Permutation null",
         "Permutation null: same points; time order randomised",
         "null_b.csv"),
        (x_c, y_c, zeros, zeros,
         "(c) AR(1) null",
         "AR(1) null: independent series with matched autocorrelation",
         "null_c.csv"),
        (x_d, y_d, zeros, zeros,
         "(d) Fourier null",
         "Fourier null: matched power spectrum; randomised phases",
         "null_d.csv"),
    ]

    print("\nSaving trajectories:")
    for x, y, sx, sy, label, desc, fname in csv_specs:
        csv_path = Path(outdir) / fname
        save_csv(x, y, sx, sy, label, desc, csv_path)
        print(f"  {csv_path}")

    # --- Figure ---
    # Panels (a) and (b) show grey reference points (noise-free signal).
    # Panels (c) and (d) show only the null realisation.
    panels = [
        (x_a, y_a, "(a) Signal (noise realisation)", x_true, y_true, sx_true, sy_true),
        (x_b, y_b, "(b) Permutation null",           x_true, y_true, sx_true, sy_true),
        (x_c, y_c, "(c) AR(1) null",                 None, None, None, None),
        (x_d, y_d, "(d) Fourier null",               None, None, None, None),
    ]

    fig, axes = plt.subplots(2, 2, figsize=(3.46, 3.40), constrained_layout=True)

    for k, (ax, (xdata, ydata, title, x_o, y_o, sx_o, sy_o)) in \
            enumerate(zip(axes.flatten(), panels)):
        draw_panel(ax, xdata, ydata, title, x_label, y_label, x_o, y_o, sx_o, sy_o)
        # Panels (a) and (b): set axis limits to include both the signal points and the null realisation, with padding for error bars.
        if k in (0, 1):
            all_x = np.concatenate([x_true, xdata])
            all_y = np.concatenate([y_true, ydata])
            if sx_o is not None:
                all_x = np.concatenate([all_x, x_true - sx_o, x_true + sx_o])
            if sy_o is not None:
                all_y = np.concatenate([all_y, y_true - sy_o, y_true + sy_o])
            pad_x = 0.08 * (all_x.max() - all_x.min())
            pad_y = 0.08 * (all_y.max() - all_y.min())
            ax.set_xlim(all_x.min() - pad_x, all_x.max() + pad_x)
            ax.set_ylim(all_y.min() - pad_y, all_y.max() + pad_y)
        else:
            # Panels (c) and (d): autoscale then add 5% margin
            ax.autoscale()
            x0, x1 = ax.get_xlim()
            y0, y1 = ax.get_ylim()
            ax.set_xlim(x0 - 0.05 * (x1 - x0), x1 + 0.05 * (x1 - x0))
            ax.set_ylim(y0 - 0.05 * (y1 - y0), y1 + 0.05 * (y1 - y0))

    cmap = plt.get_cmap("viridis")
    sm   = plt.cm.ScalarMappable(cmap=cmap, norm=mcolors.Normalize(vmin=1, vmax=N))
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=axes, orientation="vertical",
                        fraction=0.03, pad=0.02, aspect=30)
    cbar.set_label("Time step", fontsize=7)
    cbar.ax.tick_params(labelsize=6)

    fig_path = str(Path(outdir) / "null_gallery.pdf")
    fig.savefig(fig_path, bbox_inches="tight", dpi=300)
    print(f"\nSaved figure: {fig_path}")
    print(f"\nNext step: run analyse_hysteresis.py on each CSV file, e.g.:")
    for *_, fname in csv_specs:
        print(f"  python analyse_hysteresis.py "
              f"{Path(outdir) / fname} --K_null 10000")
    plt.close(fig)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description=(
            "Generate null gallery figure and save trajectories as CSV. "
            "Requires signal_a.csv from signal_gallery.py. "
            "Run analyse_hysteresis.py on the CSV files for the analysis."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--signal_csv", type=str, default="results/signal_a.csv",
                        help="Path to signal_a.csv from signal_gallery.py.")
    parser.add_argument("--seed",       type=int, default=43,
                        help="Random seed (should differ from signal_gallery seed).")
    parser.add_argument("--outdir",     type=str, default="results")
    args = parser.parse_args()

    plot_null_gallery(
        signal_csv = args.signal_csv,
        seed       = args.seed,
        outdir     = args.outdir,
    )
