"""
signal_gallery.py
=================
Generate Fig. X (signal gallery) of Terzic (2026): four representative trajectory types in the hardness ratio--flux (HR, F) plane.

This script does two things only:
  1. Generates and saves four example trajectories as CSV data files.
  2. Produces the signal gallery figure.

It does NOT perform any statistical analysis. The analysis (A_norm, closure and cancellation diagnostics, MC uncertainty propagation, p-values) should be performed separately by running analyse_hysteresis.py on the saved CSV files, exactly as one would for real observational data.

Output files
------------
All written to --outdir (default: results/):

  signal_gallery.pdf
      The 2x2 figure with the four example trajectories.

  signal_a.csv, signal_b.csv, signal_c.csv, signal_d.csv
      One CSV file per trajectory, with the following format:

          # Trajectory: (a) Clean single loop
          # Generated by signal_gallery.py (seed=42; pool_index=777)
          # Columns: F (A.U.); HR; s_F; s_HR
          # F (A.U.) : flux (normalised to quiescent = 1)
          # HR       : hardness ratio (normalised to quiescent = 1)
          # s_F      : 1-sigma uncertainty on F (fractional: s_F  = sigma_noise * F)
          # s_HR     : 1-sigma uncertainty on HR (fractional: s_HR = sigma_noise * HR)
          F (A.U.),HR,s_F,s_HR
          1.456,1.234,0.073,0.062
          ...

      These files are the input for analyse_hysteresis.py (see below).

Input format for analyse_hysteresis.py
---------------------------------------
analyse_hysteresis.py expects a CSV file where the first non-comment line is the header row with four column names (used as axis labels). All subsequent lines are data rows read by column position. Rows beginning with '#' are treated as comments and ignored. Example usage:

    python analyse_hysteresis.py signal_a.csv --K_null 10000

This will compute A_norm; R_cancel; f_closure; d_closure; the MC uncertainty interval for A_norm; and all four p-values (p_perm; p_AR; p_Fourier; p_full).

Trajectory selection
--------------------
Trajectories are drawn from a pool of K randomly sampled asymmetric Gaussian flares (see Sect. 4 of the paper). The four panels are selected from this pool by index (1-indexed, reproducible via --seed):

  (a) #777  Clean single loop      -- large |A_norm|, large R_cancel
  (b) #225  Incomplete path        -- large f_closure, large d_closure
  (c) #839  Figure-eight           -- small |A_norm|, small R_cancel
  (d) #543  Overlapping paths      -- small |A_norm|, large R_cancel

The pool indices and seed are fixed to reproduce the paper figure.
To explore other trajectories, use --idx_a/b/c/d and --seed.
Note: the trajectory labels ('Clean single loop', etc.) only apply to the default configuration (seed=42, K=1000, default indices). Using different values will produce different trajectories with potentially misleading labels.

Flare model
-----------
HR(t) = 1 + A_HR * exp(-0.5 * ((t - t_HR) / sigma_HR_pm)^2)
F(t)  = 1 + A_F  * exp(-0.5 * ((t - t_F)  / sigma_F_pm)^2)

where sigma_HR_pm = sigma_HR_rise for t < t_HR, sigma_HR_decay otherwise, and analogously for F. The time delay is delta_t = t_F - t_HR.
Measurement uncertainties are fractional:
  s_f  = sigma_noise * F
  s_hr = sigma_noise * HR

Usage
-----
    python signal_gallery.py [options]

    Key options:
      --K       INT    Pool size (default 1000)
      --seed    INT    Random seed (default 42)
      --outdir  STR    Output directory (default results)
      --idx_a/b/c/d INT  Pool indices for each panel (default as above)

    To reproduce the paper figure exactly, use the defaults.

Dependencies
------------
    numpy, matplotlib
    generate_candidates.py  -- flare model and pool generation

Author: T. Terzić <tterzic@phy.uniri.hr>
License: MIT
"""

import argparse
import sys
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

sys.path.insert(0, str(Path(__file__).parent))
from generate_candidates import asymmetric_gaussian, make_trajectory, generate_pool

# ---------------------------------------------------------------------------
# Matplotlib style -- A&A single-column compatible
# ---------------------------------------------------------------------------
plt.rcParams.update({
    "font.family"    : "serif",
    "font.size"      : 8,
    "axes.labelsize" : 8,
    "axes.titlesize" : 8,
    "xtick.direction": "in",
    "ytick.direction": "in",
    "xtick.top"      : True,
    "ytick.right"    : True,
    "xtick.labelsize": 7,
    "ytick.labelsize": 7,
    "figure.dpi"     : 200,
})

# ---------------------------------------------------------------------------
# Save trajectory as CSV
# ---------------------------------------------------------------------------

def save_csv(x, y, sx, sy, label, pool_index, seed, path):
    """
    Save a trajectory to a CSV file readable by analyse_hysteresis.py.

    The first non-comment line is the header row. Its four comma-separated values are used as axis labels in figures and output tables:
      col 0 = x observable label  (e.g. 'F (A.U.)')
      col 1 = y observable label  (e.g. 'HR')
      col 2 = x uncertainty label (e.g. 's_F')
      col 3 = y uncertainty label (e.g. 's_HR')

    Comment lines (starting with #) are ignored by the analysis code.

    Parameters
    ----------
    x, y : ndarray    F and HR coordinates
    sx, sy : ndarray  1-sigma uncertainties on x and y
    label : str               Human-readable label (e.g. '(a) Clean single loop')
    pool_index : int          1-indexed pool index (for reproducibility)
    seed : int                Random seed used to generate the pool
    path : str or Path        Output file path
    """
    with open(path, "w") as fh:
        fh.write(f"# Trajectory: {label}\n")
        fh.write(f"# Generated by signal_gallery.py (seed={seed}; pool_index={pool_index})\n")
        fh.write("# Columns: F (A.U.); HR; s_F; s_HR\n")
        fh.write("# F (A.U.) : flux (normalised to quiescent = 1)\n")
        fh.write("# HR       : hardness ratio (normalised to quiescent = 1)\n")
        fh.write("# s_F      : 1-sigma uncertainty on F (fractional: s_F  = sigma_noise * F)\n")
        fh.write("# s_HR     : 1-sigma uncertainty on HR (fractional: s_HR = sigma_noise * HR)\n")
        fh.write(f"# To analyse: python analyse_hysteresis.py {Path(path).name} --K_null 10000\n")
        fh.write("F (A.U.),HR,s_F,s_HR\n")
        for i in range(len(x)):
            fh.write(f"{x[i]:.6f},{y[i]:.6f},{sx[i]:.6f},{sy[i]:.6f}\n")


# ---------------------------------------------------------------------------
# Draw one panel
# ---------------------------------------------------------------------------

def draw_panel(ax, x, y, sx, sy, title, x_label="x", y_label="y"):
    """Draw one trajectory panel with fractional error bars.
    x_label and y_label are used as axis labels (from the CSV header row).
    """
    N = len(x)
    cmap   = plt.get_cmap("viridis")
    colors = cmap(np.linspace(0.15, 0.90, N))

    for i in range(N):
        ax.errorbar(x[i], y[i], xerr=sx[i], yerr=sy[i],
                    fmt="none", ecolor=colors[i], elinewidth=0.6,
                    capsize=1.5, capthick=0.6, zorder=2)

    ax.plot(x, y, "-", color="0.78", lw=0.7, zorder=1)

    for i in range(N):
        ax.scatter(x[i], y[i], color=colors[i], s=12, linewidths=0, zorder=3)

    # Start = circle, end = square
    ax.scatter(x[0],  y[0],  marker="o", s=20, color=colors[0],
               edgecolors="k", linewidths=0.5, zorder=4)
    ax.scatter(x[-1], y[-1], marker="s", s=20, color=colors[-1],
               edgecolors="k", linewidths=0.5, zorder=4)

    # Direction arrow at the largest gap between consecutive points
    dists  = np.sqrt(np.diff(x)**2 + np.diff(y)**2)
    i_arr  = int(np.argmax(dists))
    ax.annotate("", xy=(x[i_arr+1], y[i_arr+1]),
                xytext=(x[i_arr], y[i_arr]),
                arrowprops=dict(arrowstyle="-|>", color="0.25",
                                lw=1.0, mutation_scale=10))

    ax.set_title(title, fontsize=7, pad=3)
    ax.set_xlabel(x_label, fontsize=7)
    ax.set_ylabel(y_label, fontsize=7)
    ax.tick_params(labelsize=6)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def plot_signal_gallery(
    K             : int   = 1000,
    N             : int   = 10,
    delta_t       : float = 1.0,
    sigma_HR_rise : float = 0.5,
    sigma_HR_decay: float = 2.0,
    sigma_F_rise  : float = 2.0,
    sigma_F_decay : float = 0.5,
    sigma_noise   : float = 0.05,
    n_sigma_rise  : float = 2.0,
    n_sigma_decay : float = 2.0,
    seed          : int   = 42,
    outdir        : str   = "results",
    idx_a         : int   = 777,
    idx_b         : int   = 225,
    idx_c         : int   = 839,
    idx_d         : int   = 543,
):
    """
    Generate the signal gallery figure and save trajectories as CSV files.

    With default parameters this reproduces the paper figure exactly.
    The trajectory labels ('Clean single loop', 'Incomplete path', etc.) describe the specific trajectories selected by the default pool indices (777, 225, 839, 543) with seed=42 and K=1000. If any of these are changed, the selected trajectories will be different and the labels will no longer be meaningful.

    Run analyse_hysteresis.py on the saved CSV files for the analysis.
    """
    rng = np.random.default_rng(seed)
    Path(outdir).mkdir(parents=True, exist_ok=True)

    # Warn if non-default parameters are used, since the trajectory labels
    # only apply to the default configuration.
    non_default = (seed != 42 or K != 1000 or
                   idx_a != 777 or idx_b != 225 or idx_c != 839 or idx_d != 543)
    if non_default:
        print("WARNING: non-default seed, K, or pool indices detected.")
        print("         The trajectory labels (Clean single loop; Incomplete path; etc.)")
        print("         describe the default paper trajectories and may not apply here.")

    kwargs = dict(
        N=N, delta_t=delta_t,
        sigma_HR_rise=sigma_HR_rise, sigma_HR_decay=sigma_HR_decay,
        sigma_F_rise=sigma_F_rise,   sigma_F_decay=sigma_F_decay,
        sigma_noise=sigma_noise,
        n_sigma_rise=n_sigma_rise,   n_sigma_decay=n_sigma_decay,
    )

    print(f"Generating pool of {K} trajectories (seed={seed})...")
    pool = generate_pool(K, kwargs, rng)
    print(f"Done. Pool size: {len(pool)}")

    selections = [
        (idx_a, "(a) Clean single loop", "a"),
        (idx_b, "(b) Incomplete path",   "b"),
        (idx_c, "(c) Figure-eight",      "c"),
        (idx_d, "(d) Overlapping paths", "d"),
    ]

    # --- Save trajectories as CSV files ---
    # These are the input files for analyse_hysteresis.py.
    print("\nSaving trajectories:")
    for idx, label, letter in selections:
        x, y, sx, sy = pool[idx - 1]
        csv_path = Path(outdir) / f"signal_{letter}.csv"
        save_csv(x, y, sx, sy, label, idx, seed, csv_path)
        print(f"  {csv_path}")

    # --- Figure ---
    # Axis labels match the CSV header row written by save_csv
    x_label = "F (A.U.)"
    y_label = "HR"

    fig, axes = plt.subplots(2, 2, figsize=(3.46, 3.40), constrained_layout=True)

    for ax, (idx, title, _) in zip(axes.flatten(), selections):
        x, y, sx, sy = pool[idx - 1]
        draw_panel(ax, x, y, sx, sy, title, x_label, y_label)

    cmap = plt.get_cmap("viridis")
    sm   = plt.cm.ScalarMappable(cmap=cmap, norm=mcolors.Normalize(vmin=1, vmax=N))
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=axes, orientation="vertical",
                        fraction=0.03, pad=0.02, aspect=30)
    cbar.set_label("Time step", fontsize=7)
    cbar.ax.tick_params(labelsize=6)

    fig_path = str(Path(outdir) / "signal_gallery.pdf")
    fig.savefig(fig_path, bbox_inches="tight", dpi=300)
    print(f"\nSaved figure: {fig_path}")
    print(f"\nNext step: run analyse_hysteresis.py on each CSV file, e.g.:")
    for _, _, letter in selections:
        print(f"  python analyse_hysteresis.py "
              f"{Path(outdir) / f'signal_{letter}.csv'} --K_null 10000")
    plt.close(fig)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description=(
            "Generate signal gallery figure and save trajectories as CSV. "
            "Run analyse_hysteresis.py on the CSV files for the analysis."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--K",              type=int,   default=1000, help="Pool size.")
    parser.add_argument("--N",              type=int,   default=10,   help="Observations per trajectory.")
    parser.add_argument("--delta_t",        type=float, default=1.0)
    parser.add_argument("--sigma_HR_rise",  type=float, default=0.5)
    parser.add_argument("--sigma_HR_decay", type=float, default=2.0)
    parser.add_argument("--sigma_F_rise",   type=float, default=2.0)
    parser.add_argument("--sigma_F_decay",  type=float, default=0.5)
    parser.add_argument("--sigma_noise",    type=float, default=0.05)
    parser.add_argument("--n_sigma_rise",   type=float, default=2.0)
    parser.add_argument("--n_sigma_decay",  type=float, default=2.0)
    parser.add_argument("--seed",           type=int,   default=42)
    parser.add_argument("--outdir",         type=str,   default="results")
    parser.add_argument("--idx_a",          type=int,   default=777)
    parser.add_argument("--idx_b",          type=int,   default=225)
    parser.add_argument("--idx_c",          type=int,   default=839)
    parser.add_argument("--idx_d",          type=int,   default=543)
    args = parser.parse_args()

    plot_signal_gallery(
        K             = args.K,
        N             = args.N,
        delta_t       = args.delta_t,
        sigma_HR_rise = args.sigma_HR_rise,
        sigma_HR_decay= args.sigma_HR_decay,
        sigma_F_rise  = args.sigma_F_rise,
        sigma_F_decay = args.sigma_F_decay,
        sigma_noise   = args.sigma_noise,
        n_sigma_rise  = args.n_sigma_rise,
        n_sigma_decay = args.n_sigma_decay,
        seed          = args.seed,
        outdir        = args.outdir,
        idx_a         = args.idx_a,
        idx_b         = args.idx_b,
        idx_c         = args.idx_c,
        idx_d         = args.idx_d,
    )
